[build]
  # Build command
  command = "npm run build:prod"
  
  # Directory to publish
  publish = "build"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.auth0.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.auth0.com https://*.auth0.com/oauth/token https://mh-automotriz-auditoria-back-end.onrender.com; frame-src 'self' https://*.auth0.com; object-src 'none'; base-uri 'self'; form-action 'self';"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API proxy (if needed)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-api.com/api/:splat"
#   status = 200
#   force = true

# Branch deploy settings
[context.production]
  command = "npm run build:prod"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
